- CUETools.ChaptersToCue/CUETools.ChaptersToCue.csproj
- CUETools.FLACCL.cmd/CUETools.FLACL.cmd.csproj
- Use $(Configuration) instead of Release in path
- Update from net40 to net47
- Fixes:
Error CS0246 The type or namespace name 'OpenCLNet' could not be found
(are you missing a using directive or an assembly reference?)
CUETools.FLACL.cmd cuetools.net\CUETools.FLACCL.cmd\Program.cs 359 N/A
- Allows straight forward initial building in Debug configuration
> Update HintPath for OpenCLNet and taglib-sharp

- CUETools.FLACCL.cmd/Program.cs
- Use Hz instead of kHz
- Fixes: https://github.com/gchudov/cuetools.net/issues/17
> CUETools.FLACL.cmd: print Hz after SampleRate

- CUETools.Codecs.TTA/CUETools.Codecs.TTA.vcxproj
The .NET version in **`CUETools.Codecs.TTA.vcxproj`** was still at v4.0.
- Update the <TargetFrameworkVersion> from v4.0 to v4.7
- Use `$(Configuration)` in `<HintPath>` for
`<Reference Include="Newtonsoft.Json">` and update from net40 to net47.
This fixes the following warning and subsequent errors:
Warning MSB3274 The primary reference "Newtonsoft.Json" could not
be resolved
> Update CUETools.Codecs.TTA.vcxproj to .NET v4.7

- CUETools.ARCUE/Program.cs
- CUETools.LossyWAV/Program.cs
Update the console output to show the current filenames:
```
ArCueDotNet.exe   -> CUETools.ARCUE.exe
LossyWAVSharp.exe -> CUETools.LossyWAV.exe
```
> Fix .exe filenames in console output

- CUETools.AccurateRip/CUETools.AccurateRip.csproj
- CUETools.CDImage/CUETools.CDImage.csproj
- CUETools.CTDB.Types/CUETools.CTDB.Types.csproj
- CUETools.CTDB/CUETools.CTDB.csproj
- CUETools.Codecs/CUETools.Codecs.csproj
- CUETools.Parity/CUETools.Parity.csproj
Sort `TargetFrameworks` in the following projects with `net20` first,
to avoid warnings from **`CUETools.CTDB.EACPlugin`**:
`  CUETools.AccurateRip, CUETools.CDImage, CUETools.CTDB,`
`  CUETools.CTDB.Types, CUETools.Codecs, CUETools.Parity`
Change order:
`  <TargetFrameworks>net47;net20;netstandard2.0</TargetFrameworks>`
->
`  <TargetFrameworks>net20;net47;netstandard2.0</TargetFrameworks>`
- Fixes the following warnings after opening **`CUETools.sln`**
in Visual Studio, e.g.:
`  The referenced project 'CUETools.AccurateRip' is targeting a higher`
`  framework version (4.7) than this project’s current target framework`
`  version (2.0). This may lead to build failures if types from`
`  assemblies outside this project’s target framework are used by any`
`  project in the dependency chain. …
> Sort selected target frameworks to avoid warnings

- CUETools/frmCUETools.Designer.cs
- CUETools/frmCUETools.cs
A check of `textBoxOffset.Text` for invalid values (empty or '-' only)
is now done in a `textBoxOffset_Validating()` event instead of
previously `textBoxOffset_TextChanged()`.
This avoids observed difficulties, when entering negative offsets,
where the zero could be in the way.
> [CUETools] Update offset entry

- CUETools/frmSettings.Designer.cs
So far, the `CheckBox` under Advanced Settings:
Tagging - "Overwrite CUE data" was only grayed out (enabled/disabled)
after clicking OK. The `CheckBox` should be enabled/disabled immediately
as soon as "Fill up missing CUE data from tags" is checked/unchecked.
- Add statement to **`frmSettings.Designer.cs`**, that wires the event to the
event handler for `chkFillUpCUE_CheckedChanged()`
- Remark: The event method calling `EnableDisable()` has already been
there before in **`frmSettings.cs`**:
```C#
private void chkFillUpCUE_CheckedChanged(object sender, EventArgs e)
{
EnableDisable();
}
```
> [CUETools] Fix gray out of setting under Tagging

- CUETools.Processor/CUESheet.cs
Detected `FLAGS` were written twice per track to the cue sheet in case of
`Test & Copy` and even multiple times, when ripping was repeated without
eject/load of the CD in between.
- Add a check, if gaps have already been detected and do not write
the `FLAGS` again.
- Fixes #41
> [CUERipper] Write FLAGS only once to cue sheet

- CUETools.CDImage/CDImage.cs
In case of a CUE sheet with more than about 99 tracks, [this](https://github.com/gchudov/cuetools.net/blob/master/CUETools.CDImage/CDImage.cs#L435) `string` constructor threw an exception, because its repetition parameter was negative.
With this patch, I was able to process such a non-standard CUE sheet successfully.
What about [this](https://github.com/gchudov/cuetools.net/blob/master/CUETools.CDImage/CDImage.cs#L409) very similar line in the same file? Does it also have to be changed? (Why does one line say `100` and the other `99`?)
> Prevent exception on non-standard CUE sheet

- CUETools.Processor/CUESheet.cs
CUETools - Encode:
Up to now, when there were more than 32 images in a folder
or in sub-folders of a cue sheet, the method `LoadAlbumArt()`
returned and the window to select an image was not displayed.
- Increase the limit from `32` to `1000`. When there are more images
than the upper limit, show a message in the progress area
and continue anyway.
- Show the progress of processed album art image files in percent.
When e.g. hundreds of image files have to be processed,
this can take a while and the user sees what's going on.
- Fixes #6
> [CUETools] Allow more than 32 album art images

- CUETools.CTDB/CUEToolsDB.cs
This fix concerns CDs with a CD-Extra data track.
The option 'Detailed log' has to be enabled in CUERipper. Up to now,
when there was a difference in CD-Extra data track length, only a comma
was written into the detailed *.accurip file. The following example is
from a CD with a CD-Extra data track length 00:47:50.
- Example, before:
```console
[ CTDBID ] Status
[020a6c01] (04/21) Has no data track, Accurately ripped
[020a6c01] (04/21) , Accurately ripped
[8625f4cf] (01/21) No match
[020a6c01] (02/21) Accurately ripped
[af64186e] (01/21) , No match
```
- Example, fixed:
```console
[ CTDBID ] Status
[020a6c01] (04/21) Has no data track, Accurately ripped
[020a6c01] (04/21) CD-Extra data track length 01:02:57, Accurately ripped
[8625f4cf] (01/21) No match
[020a6c01] (02/21) Accurately ripped …
```
> Fix CD-Extra data track info in detailed log

- CUERipper/frmCUERipper.cs
Up to now, entered metadata was cleared and lost, when `UpdateDrive()` or
`UpdateDrives()` was called after device change events. This happened for
example in case of a `DBT_DEVNODES_CHANGE` event. Typical triggers for
this event are often not even CD drive related, like insert/eject of
USB sticks, disconnection or connection of a Bluetooth mouse etc.
- In order to avoid loss of entered metadata in case of such events,
save the data first before calling the methods `UpdateDrive()`
or `UpdateDrives()`.
- The entered metadata is now also saved, when a CD is ejected.
- Fixes #20
> [CUERipper] Save metadata before UpdateDrive(s)

- CUETools.Processor/CUESheet.cs
EAC log files are encoded using `UTF-16LE`. Preserve this encoding in
case of EAC log files, which contain a log checksum. This way, the
copied log file stays unchanged and the checksum can still be verified
using EAC's **`CheckLog.exe`**
> [CUETools] Preserve EAC log file encoding

- CUETools.Processor/CUELine.cs
So far, cue sheets using tabs for indentation could not be parsed and
an error message was shown.
- Fixes #65
> Support tabs for indentation in cue sheets

- Bwg.Scsi/Messages.de-DE.resx
- CUERipper/CUERipper.csproj
- CUERipper/Properties/Resources.de-DE.resx
- CUERipper/frmCUERipper.de-DE.resx
- CUERipper/frmCUERipper.resx
- CUERipper/frmFreedbSubmit.de-DE.resx
- CUETools.CLParity/CUETools.CLParity.csproj
- CUETools.CLParity/Properties/Resources.de-DE.resx
- CUETools.Codecs.FLACCL/CUETools.Codecs.FLACCL.csproj
- CUETools.Codecs.FLACCL/Properties/Resources.de-DE.resx
- CUETools.Codecs.Flake/Properties/Resources.de-DE.resx
- CUETools.Codecs.WMA/Properties/Resources.de-DE.resx
- CUETools.Ripper.SCSI/Resource1.de-DE.resx
- CUETools/CUETools.csproj
- CUETools/Properties/Resources.de-DE.resx
- CUETools/frmCUETools.de-DE.resx
- CUETools/frmChoice.de-DE.resx
- CUETools/frmSettings.de-DE.resx
- CUETools/frmSettings.resx
- CUETools/frmSubmit.de-DE.resx
Update German translation
- Use extension [ResXManager](https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager) 1.48.3862 for editing
- CUETools:
- CUETools\frmCUETools.de-DE.resx:
- Update and add German translations
- Add line breaks to the long ToolTip texts of
`chkWriteArTagsOnConvert` and `chkWriteARTagsOnVerify`
- CUETools\frmChoice.de-DE.resx:
Update German translation
Remove translations without source entry
- CUETools\frmSettings.de-DE.resx
Update and add German translations
Remove duplicate entries
Remove translations without source entry. These translations were
leftovers in frmSettings.de-DE.resx
- CUETools\frmSettings.resx:
Fix a typo in the source string of `textBoxDecoderName.ToolTip`:
encoder->decoder
- CUETools\frmSubmit.de-DE.resx:
Minor updates
- …
> Update German translation

- CUETools.Codecs.WMA/AudioDecoder.cs
- CUETools.Codecs.WMA/AudioEncoder.cs
- Fixes the following error messages, when using wma codec:
`Exception: Constructor on type`
`'CUETools.Codecs.WMA.AudioDecoder' not found.`
`'CUETools.Codecs.WMA.AudioEncoder' not found.`
- Resolves #74
- Screenshots of error messages:
> [CUETools.Codecs.WMA] Fix constructors

- CUETools/frmCUETools.de-DE.resx
When the language was set to German, CUETools was still showing the
old **`cue.ico`** instead of the current **`cue2.ico`**
This is how the icon looked before in the taskbar:
After removal of the old icon, it looks as expected:
> Remove old icon from frmCUETools.de-DE.resx

- ttalib-1.1/TTALib.vcxproj
Fixes the following compiler warnings:
- Win32, x64:
`cl : Command line warning D9035: option 'Ze' has been deprecated`
`and will be removed in a future release`
- x64:
`cl : Command line warning D9002: ignoring unknown option '/arch:SSE'`
- Background info:
The `/Ze` option is deprecated because its behavior is on by default.
https://docs.microsoft.com/en-us/visualstudio/msbuild/cl-task
`SSE` is only relevant for x86
https://docs.microsoft.com/en-us/cpp/build/reference/arch-x86
> [TTALib] Get rid of compiler warnings

- CUERipper/frmCUERipper.Designer.cs
- CUERipper/frmCUERipper.resx
- CUETools/frmCUETools.Designer.cs
- CUETools/frmCUETools.resx
Restore the `ImageScalingSize` to default settings, which is (16, 16).
As a side effect of commit 16fccfe, the `ImageScalingSize` was set to
(24, 24), which led to over-sized images. In case of `toolStripInput`
and `toolStripOutput` the images were scaled non-proportionally and
looked squashed.
- CUETools:
- Reset the `ImageScalingSize` of:
`statusStrip1`
`toolStripCorrectorFormat`
`toolStripInput`
`toolStripOutput`
`toolStripMenu`
`contextMenuStripFileTree`
- Restore `toolStripProgressBar2.Size` to `120, 23`
- Restore $this.MinimumSize to `699, 537`
- CUERipper:
- Reset the `ImageScalingSize` of: `statusStrip1`
- Restore `$this.MinimumSize` to `680, 487`
- The above mentioned modifications were applied and the rest of the
changes result from saving the forms with Visual Studio.
- The …
> [CUETools, CUERipper] Restore ImageScalingSize

- CUERipper/Properties/Settings.Designer.cs
- CUERipper/Properties/Settings.settings
- CUERipper/app.config
- CUETools.Processor/CUESheet.cs
- Freedb/FreedbHelper.cs
[gnudb.org](https://gnudb.org) has continued to provide the Freedb.org database after
Freedb.org was shutdown.
> Switch from freedb.org to gnudb.org

- CUETools/frmSettings.resx
- Settings - Tagging - Album Art:
`labelAlbumArtMaximumResolution` was slightly overlapping with
`textBoxAlArtFilenameFormat`. Add a margin of 3 to the top and the
bottom and adjust `Location` and `Size` accordingly.
- Settings - HDCD - HDCD options:
Add `grpHDCD.AutoSize`, which allows translations like German, which
require more space, to fit.
> [CUETools] Update frmSettings.resx

- CUERipper/CUERipper.csproj
- CUERipper/Properties/AssemblyInfo.cs
- CUETools/CUETools.csproj
- CUETools/Properties/AssemblyInfo.cs
- CUETools/frmCUETools.de-DE.resx
- CUERipper\CUERipper.csproj
Fix incorrect `ApplicationVersion 2.1.4.0` and set it to `1.0.0.%2a`
like in the other .csproj files. Set `ApplicationRevision` to `0`
- CUERipper\Properties\AssemblyInfo.cs
Correct version in `AssemblyVersion` and `AssemblyFileVersion`
1.9.0.0 -> 2.1.7.0
- CUETools\CUETools.csproj
Fix incorrect `ApplicationVersion 2.0.3.%2a` and set it to `1.0.0.%2a`
like in the other .csproj files. Set `ApplicationRevision` to `0`
- CUETools\Properties\AssemblyInfo.cs
Update `AssemblyTitle` and `AssemblyProduct` to `"CUETools"`
- CUETools\frmCUETools.de-DE.resx
- Correct the translation of "Create CUE sheet", which also reduces
the length of the translation, so that it fits better.
- Remove the following leftovers:
checkBoxCorrectorOverwrite.Size
checkBoxDontGenerate.Size …
> [CUERipper, CUETools] Various minor corrections

- CUETools.Codecs.FLACCL/FLACCLWriter.cs
- CUETools.FLACCL.cmd/Program.cs
The constructor parameters of `Activator.CreateInstance()` were updated
in **`CUETools.Processor\AudioReadWrite.cs`** as of commits 16fccfe and
e1f8906. The parameter `"settings"` was added in front of `path` and `IO`,
which required an update to the order of constructor parameters in
several codecs.
- Fixes the following error message, when using FLACCL codec:
`Exception: Constructor on type`
`'CUETools.Codecs.FLACCL.AudioEncoder' not found.`
- This is a follow-up commit to 18c6c1a
- Resolves #82
> [CUETools.Codecs.FLACCL] Fix constructor

- CUERipper/frmCUERipper.de-DE.resx
- CUERipper/frmCUERipper.resx
- CUETools/frmCUETools.Designer.cs
- CUETools/frmCUETools.de-DE.resx
- CUETools/frmCUETools.resx
- CUETools/frmChoice.de-DE.resx
[CUERipper] Add access key shortcuts
So far, there have not been any access key shortcuts in CUERipper.
- Add the following access key shortcuts:
Alt+G ... Go
Alt+P ... Pause
Alt+A ... Abort
Alt+M ... Meta
Alt+T ... Tracks
Alt+R ... Reload
Alt+E ... Eject
Alt+V ... V/A
Alt+C ... Codepage
Alt+S ... Submit
Alt+O ... Options
- Add corresponding access key shortcuts to the German translation
[CUETools] Update access key shortcuts
- Update the access key for "Encode" to Alt+c, because Alt+E is
also used for "Embedded"
- Add access keys:
Alt+O ... Output:
Alt+I ... Input:
Alt+S ... Settings
[CUETools] Make settings accessible using Alt+S
- Change the DisplayStyle from Image to ImageAndText for the
following buttons:
toolStripButtonShowLog
toolStripButtonSettings
toolStripButtonHelp …
> Add and update access key shortcuts

- .github/workflows/CI-windows.yml
- .github/workflows/release-windows.yml
- .gitmodules
- README.md
- ThirdParty/submodule_flac_CUETools.patch
An issue with currently used libFLAC version 1.3.2 git 45f7d41 has been
reported [1]. Compression efficiency was affected, depending on CPU
type.
- Used the following commands, to switch the flac submodule to upstream
[xiph/flac](https://github.com/xiph/flac) repo and checkout commit xiph/flac@27c6157:
```sh
git submodule set-url ThirdParty/flac https://github.com/xiph/flac.git
git submodule update --init --recursive --remote ThirdParty/flac
pushd ThirdParty/flac/
git checkout 27c615706cedd252a206dd77e3910dfa395dcc49
popd
```
- Add patch based on commits of [gchudov/flac](https://github.com/gchudov/flac) github repo
"project file modified to build the .dll for use with CUETools"
(commits 36fce5b, 6735ddd, 8f4f296, 900bf23), which is applied using:
`git apply --directory=ThirdParty/flac …
> Update libFLAC to 1.3.3 git 27c6157

- CUETools.Ripper.SCSI/SCSIDrive.cs
- `C2ErrorMode.Mode294` does not work for these drives:
LG GH24NSD1, ASUS DRW-24D5MT. Try `Mode296` first
`CUETools.Ripper.SCSI.SCSIException:`
`'Error reading CD: medium error: UNRECOVERED READ ERROR'`
- Resolves #19
> Fix C2 error mode for selected drives

- CUETools.Processor/General.cs
An issue in CUETools 2.1.8 has been reported [1], if an album title
contains "..." at the end. Three dots at the end of a directory name
are supposed to cause issues. In CUETools 2.1.7, "..." was
automatically removed from the directory name.
- Add a check to remove "...\" from the `DirectoryName` to retain the
behavior as in CUETools 2.1.7
- Fixes the following `Exception: Could not find a part of the path`
[1] https://hydrogenaud.io/index.php?topic=120854.0
> Allow three dots at the end of album titles

- CUETools/collect_files.bat
Add copying of `interop\EAC\Newtonsoft.Json.dll` to **`collect_files.bat`**
- An issue concerning missing CTDB results in EAC log files has been
reported [1]
- The `Newtonsoft.Json.dll` file is required and originates from:
`Newtonsoft.Json.11.0.1.nupkg\lib\net20\Newtonsoft.Json.dll`
- Resolves #100
[1] https://hydrogenaud.io/index.php?topic=120871.0
> [EACPlugin] Add Newtonsoft.Json.dll

- .github/workflows/CI-windows.yml
- .github/workflows/release-windows.yml
- .gitmodules
- README.md
- ThirdParty/submodule_WavPack_CUETools_VS2017.patch
- ThirdParty/submodule_WavPack_CUETools_VS2019.patch
- Used the following commands, to switch the WavPack submodule to
upstream [dbry/WavPack](https://github.com/dbry/WavPack) repo and checkout commit dbry/WavPack@2ce3c06 (5.4.0):
```sh
git submodule set-url ThirdParty/WavPack \
https://github.com/dbry/WavPack.git
git submodule update --init --recursive --remote ThirdParty/WavPack
pushd ThirdParty/WavPack/
git checkout 2ce3c069be548e82ea9c05741ace6583e549c6de
popd
```
- Add patch based on commits of GitHub repo [gchudov/WavPack](https://github.com/gchudov/WavPack)
"Converted projects to work with VS2017 and configured wavpackdll for
use with CUETools."
(commits c2d60b1, 9b59bcd), which is applied using:
`git apply --directory=ThirdParty/WavPack ThirdParty/submodule_WavPack_CUETools_VS2017.patch`
- A patch for compiling with VS2019 is …
> Update WavPack to 5.4.0

- CUERipper/frmCUERipper.resx
- The Russian translations of "Reload" and "Codepage" need slightly
more space to fit into the buttons. Add AutoSize property to
buttonReload and buttonEncoding.
> [CUERipper] Add AutoSize to further buttons

- CUETools.Processor/CUEConfigAdvanced.cs
This PR contains the fix as suggested by @RDamman in https://github.com/gchudov/cuetools.net/issues/113#issuecomment-904517997:
Call to the right (copy) constructor of the base class in
CUEConfigAdvanced.cs
- Resolves #113
> Fix CUEConfigAdvanced copy constructor

- CUETools.Processor/CUESheet.cs
In case of CD-Singles with one track, the tags `AccurateRip`, `CTDB` and
`CDTOC` were only written upon verify or encode , if the CD-Single
had been ripped in image mode with embedded `CUESheet`.
- Enable writing of these tags also for CD-Singles (with one track),
which have been ripped in track mode.
- Resolves #121
> Fix writing of tags for CD-Singles

- CUETools.Processor/CUESheet.cs
CUETools currently supports reading of cuesheets in `ANSI` or `UTF-8-BOM`
format. In case of `UTF-8` files without BOM, issues with special
characters in filenames and cuesheets can occur.
- Use method `StreamReader_UTF_ANSI()` in `CorrectAudioFilenames()`.
Detect, if file is `UTF-8-BOM` or `UTF-8` without BOM. Otherwise
fall back to default encoding, which is typically `ANSI`.
> Support UTF-8 encoding when reading cuesheets

- CUETools.ALACEnc/Program.cs
- CUETools.FLACCL.cmd/Program.cs
- CUETools.FlaCudaExe/Program.cs
- CUETools.Flake/Program.cs
The command line tools `CUETools.ALACEnc.exe`, `CUETools.FLACCL.cmd.exe`
and `CUETools.Flake.exe` allow usage of "-" (without quotes) for `stdin`.
Add this info to the command line help output.
- Resolves #141
> Add info about stdin

- CUETools.CTDB.EACPlugin/FormMetadata.cs
The coverartarchive.org site stopped supporting TLS 1.1.
EAC plugin is built for .NET 2.0, which doesn't use TLS 1.2 by default.
- Switch to TLS 1.2
- Resolves #150
> EACPlugin: Use TLS 1.2 for coverart download

- CUETools.Ripper.SCSI/SCSIDrive.cs
- `C2ErrorMode.Mode294` does not work for these drives:
PIONEER DVR-S21, BDR-XD07U. Try `Mode296` first.
- Fixes the following exceptions:
- DVR-S21:
`CUETools.Ripper.SCSI.SCSIException:`
`'Error reading CD: medium error: UNRECOVERED READ ERROR'`
- Resolves #133
- BDR-XD07U:
`Exception: Error reading CD: IoctlFailed`
- Resolves #155
> Fix C2 error mode for two Pioneer drives

- CUERipper/frmCUERipper.cs
Part of commit 9d2886e, `UpdateDrive()` has been added to
`buttonEjectDisk_Click()`, in order to fix #115.
However, `UpdateDrive()` clears modified metadata.
- Save the metadata before `UpdateDrive()`, similar to
a2b12d1
> [CUERipper] Save metadata before Eject

- CUETools.Processor/CUESheet.cs
If "Verify using CTDB" is disabled, an exception can occur in
`LoadAndResizeAlbumArt()`. `CTDB` is `null` in this case and
`CTDB.FetchFile(imageMeta.uri, ms)` will throw the exception.
The exception occurs after selecting specific entries in the
"Select best match" window for albums, when there are different album
arts available from coverartarchive.org. In this case, the window for
selecting the album art is not shown anymore and the exception appears.
- Use "`try`" and `catch` the exception
- Fixes the following error:
`Exception Object reference not set to an instance of an object.`
- This commit is an addition to 3f121a8
- Resolves #148
> [CUETools] Fix CTDB.FetchFile Exception

- CUERipper/frmCUERipper.cs
Up to now, entered metadata was lost when closing CUERipper, if it
had not been saved before by another event (e.g. Go, Eject).
- Save the metadata anyway, when closing CUERipper.
> [CUERipper] Save metadata before Exit

- ThirdParty/submodule_taglib-sharp_CUETools.patch
When adding album art files to flac files, the picture dimension tags
in the `METADATA block` have been zero:
```console
width: 0
height: 0
```
- Modify **`src/TaglibSharp/Flac/Picture.cs`**
Calculate `Width`, `Height` and `ColorDepth` from the album art
- Remark: In CUETools, `TagLib.IPicture` is used for the album art, which
does not support setting the `Width` or `Height`. However, `IPicture` is
flexible for tagging different audio formats. `Width`, `Height`,
`ColorDepth` and `IndexedColors` are special for `TagLib.Flac.Picture`.
Remark: support for counting the number of colors is not added by this
modification for unnecessary computational reasons.
- Resolves #146 (remaining part concerning width and height)
> Fix width and height of album art in flac tags

- CUERipper/frmCUERipper.cs
The issue occurred in case of CDs, where the first track is a data
track. After editing the title of the last audio track, the index was
out of range.
- `listTracks_AfterLabelEdit()`:
Correct the index of `data.selectedRelease.metadata.Tracks[]` by adding
"`1`" and subtracting "`selectedDriveInfo.drive.TOC.FirstAudio`", which
is `1` if the first track is audio, and `2` if the first track is data.
- Fixes the following error:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at CUERipper.frmCUERipper.listTracks_AfterLabelEdit(Object sender, LabelEditEventArgs e)
```
- Resolves #126
> Fix index error when 1st track is data track

- CUETools.Ripper.SCSI/SCSIDrive.cs
**`HL-DT-ST BD-RE BU40N`**. Try `Mode296` first.
- Resolves #164
> Fix C2 mode for HL-DT-ST BD-RE BU40N

- CUETools.Ripper.SCSI/SCSIDrive.cs
**`Slimtype - DVD A DU8AESH`**. Try `Mode296` first.
- Resolves:
https://hydrogenaud.io/index.php?topic=122161.0
> Fix C2 mode for Slimtype - DVD A DU8AESH

- CUETools/frmCUETools.cs
Since 3f121a8 no album art is used in case of multiple album art files,
if no album art is selected in the dialog and also in batch mode [1].
The batch mode behavior before was to use the first one from the list
of found album art files.
- Return index 0 instead of -1 from the album art selection dialog in
case of batch mode.
- Resolves:
https://hydrogenaud.io/index.php?topic=122155.0
[1] https://github.com/gchudov/cuetools.net/blob/ddec34a1ff613fe63522e9a0a48f84f3e3356395/CUETools.Processor/CUESheet.cs#L1847
> [CUETools] Use first album art in batch mode

- ThirdParty/submodule_flac_CUETools.patch
FLAC 1.3.4 has been released on 2022-02-20.
- The version of libFLAC used in CUETools (xiph/flac@27c6157) has
already been close to version 1.3.4. Update to the official release.
- Used the following commands, to checkout tag 1.3.4 (commit xiph/flac@1151c93):
```console
pushd ThirdParty/flac/
git pull
git checkout 1.3.4
popd
```
- Update `submodule_flac_CUETools.patch` to 1.3.4
> Update libFLAC to 1.3.4

- CUETools.Codecs/CUEToolsCodecsConfig.cs
So far, **`flac.exe`** had to be added manually including setting of
suitable parameters. Simplify adding **`flac.exe`** to `Encoders`.
- Add **`flac.exe`** with parameters "`-%M -P %P - -o %O`" and default
compression level `5` to **`CUEToolsCodecsConfig.cs`**
- Avoids the following initial message, when the "Encoder mode"
slider has not yet been set:
`flac.exe has exited prematurely with code 1: The pipe has been ended.`
> Add flac.exe to Encoders

- CUETools.Ripper.SCSI/SCSIDrive.cs
- `C2ErrorMode.Mode294` does not work for these drives:
`ASUS DRW-24F1ST d`, `PIONEER BD-RW BDR-XD05`. Try `Mode296` first.
- Resolves:
https://hydrogenaud.io/index.php?topic=122176.0
- Introduce variable `pathNoSpace` for cases with one or more spaces in
the identifier string of a drive. Example: "DRW-24F1ST&nbsp;&nbsp;&nbsp;d"
> Fix C2 mode for further drives

- CUETools.Ripper.Console/Program.cs
Do not automatically overwrite existing files. Use a unique filename.
- Add a counter in brackets, if the file exists, e.g.:
cdimage.wav, cdimage (1).wav, cdimage (2).wav etc.
- Resolves: https://hydrogenaud.io/index.php?topic=117971.0
> CUETools.Ripper.Console.exe: Prevent overwriting

- CUERipper/frmCUERipper.Designer.cs
- CUERipper/frmCUERipper.cs
- CUETools/frmCUETools.Designer.cs
- CUETools/frmCUETools.cs
The output template needs to contain an extension, which is
typically ".cue". This is relevant in cases, where e.g. the album or
artist contains a dot. If the default extension ".cue" has been
removed, then the text after the dot will be treated as the extension,
which can lead to undesired behavior.
- Check, if the output template contains ".cue" at the end and add it
if missing.
- The check for ".cue" is done after editing the output template in
CUERipper or CUETools and also when loading the settings file for the
case that it has been edited.
- Resolves:
Weird results when there are dots in filenames
https://hydrogenaud.io/index.php?topic=122028.0
Fallback when user doesn't add extension to template
https://hydrogenaud.io/index.php?topic=118915.msg980706#msg980706
> Make sure output template contains extension .cue

- CUETools/frmBatch.cs
So far, the profile settings 'Use CTDB' or 'Verify Using CTDB' have not
been considered, when running `CUETools.exe` from the command line using
`/<profile>`
- Consider the settings `CUEToolsDBLookup` (`_CTDBVerify`) and
`CTDBVerifyOnEncode` (`_CTDBVerifyOnEncode`)
- Resolves:
https://hydrogenaud.io/index.php?topic=118915.msg980707#msg980707
> CUETools.exe /<profile>: Enable CTDB verification

- CUEPlayer/Properties/DataSources/Output.datasource
- CUEPlayer/Properties/DataSources/frmCUEPlayer.datasource
- CUERipper/Properties/DataSources/frmCUERipper.datasource
- CUERipper/frmCUERipper.resx
- CUERipper/frmFreedbSubmit.resx
- CUETools/Properties/DataSources/CUETools.Processor.CUEConfig.datasource
- CUETools/frmCUETools.resx
Several `.resx` and `.datasource` files contained the exact version
information of CUETools, which is not necessary. Simplify these
entries, so that they are not updated upon each release of CUETools.
- Replacements:
`CUEControls, Version=2.2.1.0` -> `CUEControls, Version=2.0.0.0`
`CUEPlayer, Version=2.2.1.0` -> `CUEPlayer, Version=2.0.0.0`
`CUETools.Processor, Version=2.2.1.0` -> `CUETools.Processor, Version=2.0.0.0`
> Simplify version entries in resx and datasource

- CUETools.Codecs/ViewModel/DecoderListViewModel.cs
- CUETools.Codecs/ViewModel/EncoderListViewModel.cs
Removing of manually added Encoders or Decoders has not yet been
implemented since the code cleanup in commits ca8bb2f, e1f8906 and
320e75d. The removal appeared only in the CUETools Advanced Settings
form, but was not saved. This was working in CUETools 2.1.7 and earlier.
- Add `ListChanged` event to `DecoderListViewModel` and
`EncoderListViewModel`. Remove the item also from the underlying list
using `RemoveAt()` method.
- Removing of manually added Encoders or Decoders is saved now in the
CUETools settings file
> Fix removing of Encoders or Decoders

- CUETools/frmSettings.Designer.cs
- CUETools/frmSettings.cs
In `CUETools - Advanced settings - Decoders`, the keys insert and delete
could not be used yet for adding or removing Decoders. Enable the
possibility to use insert and delete keys like in the `Formats` or
`Encoders` tab.
- Add event `listBoxDecoders.KeyDown`
- The method for the `KeyDown` event has already been available.
However, rename it according to the name of the `ListBox` control:
`listViewDecoders_KeyDown` -> `listBoxDecoders_KeyDown`
Remark: the name is now analogous to `listBoxEncoders_KeyDown`
> Enable Insert and Delete key for Decoders

- ThirdParty/submodule_WavPack_CUETools.patch
- Used the following commands, to update the [dbry/WavPack](https://github.com/dbry/WavPack) submodule to
commit dbry/WavPack@89ef99e (5.5.0):
```sh
pushd ThirdParty/WavPack/
git pull
git checkout 89ef99e84333534d9d43093a5264a398b5f1e14a
popd
```
- Update `submodule_WavPack_CUETools.patch` accordingly
> Update WavPack to 5.5.0

- CUERipper/CUERipperConfig.cs
- CUERipper/frmCUERipper.cs
- CUETools.Ripper.Console/Program.cs
- CUETools.Ripper.SCSI/SCSIDrive.cs
- CUETools.Ripper/DriveC2ErrorModeSetting.cs
- CUETools.Ripper/Ripper.cs
There are some drives, where automatic detection of the `C2ErrorMode`
does not work. CUETools already contains a fix for specific drives,
where `Mode294` does not work properly. However, there are still drives,
where setting the `C2ErrorMode` to a specific value helps.
- Add a setting for the `C2ErrorMode`
- Values for the drive specific setting "`DriveC2ErrorModes`" are:
`0 (None), 1 (Mode294), 2 (Mode296), 3 (Auto)`
- `CUETools.Ripper.Console.exe`, add option:
`-C, --c2mode <int>       use specific C2ErrorMode, 0 (None), 1 (Mode294), 2 (Mode296), 3 (Auto);`
> [CUERipper] Add setting for C2ErrorMode

- CUERipper/frmCUERipper.Designer.cs
- CUERipper/frmCUERipper.cs
- CUERipper/frmCUERipper.de-DE.resx
- CUERipper/frmCUERipper.resx
- CUERipper/frmCUERipper.ru-RU.resx
Add a ComboBox left to the Read offset, which allows to select the
C2ErrorMode for each drive, if required. The default setting is `Auto`,
which preserves the behavior of CUERipper.
- Remove `lblWriteOffset` to free space for the new ComboBox
`bnComboBoxC2ErrorModeSetting`
- Update `TabIndex` considering the added `bnComboBoxC2ErrorModeSetting`
- Add ToolTip to `bnComboBoxC2ErrorModeSetting` and `numericWriteOffset`
- Update the translation files and move the translation of the removed
`lblWriteOffset.Text` to `numericWriteOffset.ToolTip`
> [CUERipper] Add GUI setting for C2ErrorMode

- CUETools.Codecs.TTA/CUETools.Codecs.TTA.cpp
Set `ttalib` as default decoder for `tta` instead of `ffmpeg.dll`.
This is a follow-up to commit 18c6c1a, where the priority has already
been updated for `libwavpack` and `MACLib`.
- Increase the priority of the `ttalib` `AudioDecoder` from `1` to `2`
- Resolves: #207
> [CUETools] Fix tta decoding exception

- CUETools.Ripper.SCSI/SCSIDrive.cs
The auto-detected `C2ErrorMode.Mode294` does not work for these drives:
PLDS DU-8A5LH, iHAS324 F. Specify the reported working `C2ErrorMode`.
- PLDS DU-8A5LH:
`C2ErrorMode.Mode296` has been reported to work.
https://hydrogenaud.io/index.php?topic=122161.msg1011466#msg1011466
- iHAS324 F
`C2ErrorMode.None` has been reported to work.
https://github.com/gchudov/cuetools.net/issues/107#issuecomment-1145410404
- Sort the list of drives, which require special attention concerning
`C2ErrorMode`
- Revise the code concerning `C2ErrorMode` of drives in order to handle
the following three cases:
* Default. Automatic detection like in the past.
`C2ErrorMode` is tried in the following order: `Mode294, Mode296, None`
* Drives, where `Mode294` was detected but not working. `Mode296` works.
Use `Mode296` …
> Fix default C2 error mode for further drives

- CUETools/collect_files.bat
- CUETools/collect_files_debug.bat
`FFmpeg.AutoGen.dll` is required by the experimental ffmpeg plugin of
CUETools.
- Update the scripts `collect_files.bat` and `collect_files_debug.bat`
- Fixes Exception: Could not load file or assembly 'FFmpeg.AutoGen,
Version=4.1.0.4, Culture=neutral, PublicKeyToken=9b7632533a381715' or
one of its dependencies. The system cannot find the file specified.
- Remark: For using the FFmpeg plugin, further dll files are required
from FFmpeg.AutoGen\FFmpeg\bin\x64 in their matching
version and need to be copied to plugins\x64\. They are not
distributed together with CUETools.
Currently, CUETools is set to use FFmpeg.AutoGen 4.1.0.4, which
requires the following FFmpeg 4.1 dlls:
avcodec-58.dll, avdevice-58.dll, avfilter-7.dll, avformat-58.dll,
avutil-56.dll, postproc-55.dll, swresample-3.dll, …
> Collect FFmpeg.AutoGen.dll

- CUETools.Codecs.ffmpeg/AudioDecoder.cs
So far, `_sampleCount` has been permanently set to `-1`. It is used for
calculating the `Length`.
- Assign value to `_sampleCount` at EOF
`Audio file length is unknown or invalid`
> FFmpeg plugin: Fix Audio file length is unknown

- CUETools/collect_files.bat
- CUETools/collect_files_debug.bat
- Checkout release 4.3.0.3 of `FFmpeg.AutoGen`. The previously used
commit in CUETools was Ruslan-B/FFmpeg.AutoGen@9bb7daa ([4.1.0.4](https://github.com/Ruslan-B/FFmpeg.AutoGen/releases/tag/4.1.0.4)).
- Use the following commands, to update the `FFmpeg.AutoGen` submodule to
commit Ruslan-B/FFmpeg.AutoGen@e0d26f8 (tag [4.3.0.3](https://github.com/Ruslan-B/FFmpeg.AutoGen/releases/tag/4.3.0.3)):
```sh
pushd ThirdParty/FFmpeg.AutoGen/
git fetch
git checkout e0d26f8a24e36b6cec25c703336eddb38a6d017e
popd
```
> Update FFmpeg.AutoGen from 4.1.0.4 to 4.3.0.3

- .github/workflows/CI-windows.yml
- .github/workflows/release-windows.yml
- README.md
- ThirdParty/submodule_flac_CUETools.patch
- Checkout release 1.4.1 of FLAC. The previously used
commit in CUETools was xiph/flac@1151c93 (1.3.4).
- Use the following commands, to update the flac submodule to
commit xiph/flac@b6fbd6b (tag 1.4.1):
```sh
pushd ThirdParty/flac/
git fetch
git checkout b6fbd6b3d97e2da4481bdbd25176f263fd6a5e75
popd
```
- Update `submodule_flac_CUETools.patch` to 1.4.1
- Resolves #217
> Update libFLAC from 1.3.4 to 1.4.1

- CUETools/frmCUETools.cs
If a single .cue file is selected in the "Multiselect Browser", `frmChoice` appears after clicking Go. When closing this form by clicking on X and hitting the Go button again, the selected .cue file will be encoded twice.
- Clear `_batchPaths` in case of `DialogResult.Cancel`, if only one .cue file has been selected in Multiselect Browser.
- Resolves #224
> Fix encoding single selected album twice

- .github/workflows/CI-windows.yml
- .github/workflows/release-windows.yml
- README.md
- ThirdParty/submodule_flac_CUETools.patch
- Checkout release 1.4.2 of FLAC. The previously used
commit in CUETools was xiph/flac@b6fbd6b (tag 1.4.1).
- Use the following commands, to update the flac submodule to
commit xiph/flac@b32e5cb (tag 1.4.2):
```sh
pushd ThirdParty/flac/
git fetch
git checkout b32e5cbf9818ca23dd22aaa75522042c16ea7d17
popd
```
- Update `submodule_flac_CUETools.patch` to 1.4.2
- Remove `nasm`. All assembler has been removed upstream (xiph/flac@75ef795).
> Update libFLAC from 1.4.1 to 1.4.2

- CUETools.Processor/CUEConfig.cs
- CUETools.Processor/CUESheet.cs
*This description was updated to reflect the changes done after feedback was received.*
When one wants to generate or update .accurip files for a whole music library that contains releases of multiple mediums.
Added a new verify script. When it is selected CueTools will skip verifying releases if a rip log is not found.
Output when the script is selected: ([directory contents](https://github.com/gchudov/cuetools.net/files/9895772/index.txt))
```
.\hires\1.flac: Audio format is not Red Book PCM..
.\log\1.flac: AR: rip accurate (7/7), CTDB: verified OK, confidence 32.
.\nolog\1.flac: Rip log is not present..
```
> Add option to skip verifying when a rip log cannot be found

- ThirdParty/submodule_WavPack_CUETools.patch
- Checkout release 5.6.0 of [dbry/WavPack](https://github.com/dbry/WavPack). The previously used
commit in CUETools was dbry/WavPack@89ef99e (tag 5.5.0).
- Use the following commands, to update the WavPack submodule to
commit dbry/WavPack@e03e8e2 (tag 5.6.0):
```sh
pushd ThirdParty/WavPack/
git fetch
git checkout e03e8e29dc618e08e7baba9636e57ba1254874ce
popd
```
- Update `submodule_WavPack_CUETools.patch` accordingly
> Update WavPack from 5.5.0 to 5.6.0

- CUETools.Processor/CUESheet.cs
So far, the tags `TRACKNUMBER` and `TRACKTOTAL` have not been copied in this case:
```
CUETools - Advanced settings - Tagging:
Write basic tags from CUE data: disabled
Copy basic tags: enabled
```
- Copy the basic tags 'Track' and 'Trackcount', if 'CopyBasicTags=1'
- Resolves #221
> Copy basic tags TRACKNUMBER and TRACKTOTAL

- CUETools.Codecs.MACLib/DecoderSettings.cs
- CUETools.Codecs.MACLib/EncoderSettings.cs
Only the first char of the MACLib version string has been shown in
Advanced Settings - Encoders - MACLib [ape] ("4" instead of "4.33").
- `MAC_VERSION_STRING` is returned as `wchar_t`, therefore use
`Marshal.PtrToStringUni` instead of `Marshal.PtrToStringAnsi`
> Show complete MACLib version string in settings

- CUETools.ALACEnc/Program.cs
- CUETools.Codecs.ALAC/ALACWriter.cs
The following stereo methods are supported using the command line
option "`-s <method>`":
`Independent = 0, Estimate = 1, Evaluate = 2, Search = 3`
Default: `Estimate` at compression level `5`.
The methods can be specified using the name or the corresponding
number, e.g.:
`CUETools.ALACEnc.exe test.wav -s Independent`
`CUETools.ALACEnc.exe test.wav -s 0`
- Add a check of the specified stereo method number for validity.
- In case of invalid method numbers:
Show usage and output "`Invalid stereo method specified.`"
- Fixes #241
- Update comments in ALACWriter.cs, `struct ALACEncodeParams` for:
`public StereoMethod stereo_method;`
Looks like the previous comments were from FLACCLWriter.cs
(FlaCudaWriter.cs). The comments contain the same info now as the
`enum StereoMethod` (see …
> CUETools.ALACEnc.exe: Add check for StereoMethod

- ThirdParty/ThirdParty_MAC_SDK_CUETools.patch
In case of ape files, which are smaller than 128 bytes, an exception
occurs during the analyzing step. For example, very short HTOA files
can be smaller than 128 bytes.
- Add an additional condition to APETag.cpp, `CAPETag::Analyze()`,
when checking for an ID3v1 tag:
`(m_spIO->GetSize() > ID3_TAG_BYTES)`
`An attempt was made to move the file pointer before the beginning`
`of the file.`
> APE: Fix exception when decoding very small files

- CUETools.Codecs.libFLAC/FLACDLL.cs
- CUETools.Codecs.libFLAC/Writer.cs
So far, an arithmetic overflow has occurred, when running CUETools
under 32-bit and using libFLAC for encoding.
See: https://hydrogenaud.io/index.php/topic,116743.0.html
- `FLAC__StreamEncoderWriteCallback`:
Use `UIntPtr bytes` instead of `long bytes`, whereas C# `UIntPtr`
matches `size_t` under 64 and 32-bit. Link to FLAC documentation:
https://xiph.org/flac/api/stream__encoder_8h.html
`Arithmetic operation resulted in an overflow.`
> libFLAC: Fix arithmetic overflow under 32-bit

- CUETools.Codecs.libFLAC/FLACDLL.cs
- CUETools.Codecs.libFLAC/Reader.cs
So far, an exception has occurred, when running CUETools
under 32-bit and using libFLAC for decoding.
- `FLAC__StreamDecoderReadCallback`:
Use `ref UIntPtr bytes` instead of `ref long bytes`, whereas C#
`UIntPtr` matches `size_t` under 64 and 32-bit.
Link to FLAC documentation:
https://xiph.org/flac/api/group__flac__stream__decoder.html
`unable to retrieve metadata`
> libFLAC: Fix unable to retrieve metadata (32-bit)

- .github/workflows/release-windows.yml
- collect_files.bat
Part of #253, `collect_files.bat` and `License.txt` have been moved to
the root of the repo.
- Update path to `collect_files.bat` in GitHub Action
`.github/workflows/release-windows.yml`
- Furthermore, update path of moved `License.txt` file in
`collect_files.bat`
> Fix path of collect_files.bat in release-windows

- CUETools.Processor/CUEConfig.cs
- CUETools.Processor/CUESheet.cs
- CUETools/frmCUETools.cs
So far, cue sheets were only written in UTF-8, if they contained
characters, which could not be encoded in the local Windows codepage.
These UTF-8 encoded cue files contain a BOM (UTF-8-BOM).
The new setting allows to always write cue sheets using `Encoding.UTF8`.
- Add setting:
`AlwaysWriteUTF8CUEFile`
Default:
`AlwaysWriteUTF8CUEFile=0`
The setting is disabled by default, to preserve previous behavior.
- For now, the setting can be modified by editing `settings.txt`:
Use bool value 1, to always write CUE sheets using UTF-8 encoding.
- The setting is available in the CUETools as well as the CUERipper
`settings.txt` file.
- Resolves:
Option to always write utf-8 CUE sheet
https://hydrogenaud.io/index.php/topic,118915.0.html#post_g07
https://hydrogenaud.io/index.php/topic,117151.0.html
> Add setting to always write UTF-8 CUE sheet

- CUETools.Codecs.ffmpeg/AudioDecoder.cs
Typically, tta files can be decoded by CUETools using ttalib. An alternative possibility of decoding tta is ffmpeg.dll. The ffmpeg AVSampleFormat of tta files is AV_SAMPLE_FMT_S16 [1].
- Add `AVSampleFormat.AV_SAMPLE_FMT_S16` to CUETools.Codecs.ffmpeg\AudioDecoder.cs
- Fixes the following exception: Specified method is not supported
- Resolves: #254
[1] https://ffmpeg.org/doxygen/3.1/group__lavu__sampfmts.html
> Allow tta decoding using ffmpeg.dll

- CUETools.ChaptersToCue/CUETools.ChaptersToCue.csproj
So far, **`CUETools.ChaptersToCue.csproj`** contained a `Reference Include`
to `TaglibSharp` with a `HintPath` to `TagLibSharp.dll`. This has worked
in VS2017 or VS2019. However, in **`VS2022`** a build error occurs during
the first attempt of building the Solution.
- CUETools.ChaptersToCue.csproj:
Add `ProjectReference` to `TaglibSharp`
- Fixes the following errors, when building using VS2022:
```
Error CS0246 The type or namespace name 'TagLib' could not be found
(are you missing a using directive or an assembly reference?)
CUETools.ChaptersToCue\Program.cs
Error CS0103 The name 'TagLib' does not exist in the current context
CUETools.ChaptersToCue\Program.cs
```
> ChaptersToCue: Add TaglibSharp ProjectReference

- CUETools.Codecs.ffmpeg/AudioDecoder.cs
- CUETools.Codecs.ffmpeg/CUETools.Codecs.ffmpeg.csproj
- Update NuGet package [FFmpeg.AutoGen](https://www.nuget.org/packages/FFmpeg.AutoGen) from 4.3.0.3 to 6.0.0.2
- CUETools.Codecs.ffmpeg\AudioDecoder.cs:
- Remove `ffmpeg.av_register_all()` due to API changes [1].
`av_register_all()` has been deprecated in ffmpeg 4.0. It is not
needed and not available anymore.
- Remove `RegisterLibrariesSearchPath()` and use `ffmpeg.RootPath`
in order to find the ffmpeg 6.0 dlls, which need to be copied to
plugins\win32 or plugins\x64 as usual.
[1] https://github.com/FFmpeg/FFmpeg/blob/master/doc/APIchanges
> Update FFmpeg.AutoGen from 4.3.0.3 to 6.0.0.2

- CUETools/frmSettings.Designer.cs
- CUETools/frmSettings.cs
- CUETools/frmSettings.de-DE.resx
- CUETools/frmSettings.resx
The setting `AlwaysWriteUTF8CUEFile` has been introduced in
commit 9e1d3f2.
- Add GUI setting "Always write UTF-8 CUE sheet" under
`CUETools - Advanced Settings - CUETools - General`
- The height of the CUETools Settings form has been increased by 17 to
accommodate the new setting.
- Add German translation of the setting
> Add GUI setting to always write UTF-8 CUE sheet

- CUERipper/frmCUERipper.Designer.cs
- CUERipper/frmCUERipper.cs
Editing Track Titles has been possible using F2. Add the same behavior
to the Metadata list. This is an additional possibility using the
keyboard instead of clicking.
- Add `listMetadata_KeyDown` event for key `F2`
- Add `listMetadata_PreviewKeyDown` event for `Enter`
Hitting Enter after editing will move to the next Metadata item now,
as in `listTracks`.
- Keys for navigation in CUERipper under Tracks or Meta:
Moving: Cursor up, Cursor down
Editing: F2, Enter, Ctrl+Tab, Ctrl+Shift+Tab, Esc
> CUERipper: Allow editing Metadata using F2

- CUETools.Ripper.SCSI/SCSIDrive.cs
**`HL-DT-ST DVDRAM GH22LS51`**. Try `Mode296` first.
- Resolves #283
> Fix C2 mode for GH22LS51

- CUETools.Processor/CUESheet.cs
The offset has been applied twice in case of the scripts "repair"
or "encode if verified".
- Any offset is already applied during the verification step.
Check if an offset has been applied.
- Resolves #265 and
https://hydrogenaud.io/index.php/topic,122081.0.html
> Avoid applying offset twice

- CUETools.Ripper.SCSI/SCSIDrive.cs
**`MATSHITA DVD-R UJ-868`**. Try `Mode296` first.
- See #296
> Fix C2 mode for UJ-868

- CUETools.Codecs.ffmpeg/DecoderSettings.cs
- CUETools.Codecs/CUEToolsCodecsConfig.cs
- CUETools/frmSettings.resx
- Add `aiff` to `Settings - Formats`. Use `ffmpeg.dll` as Decoder.
- Slightly increase height of `listViewFormats` in order to avoid
initial scrollbars in `Settings - Formats`, after aiff has been added.
- In order to decode AIFF files using CUETools, ffmpeg 6.0 dlls
need to be copied to `plugins\win32` or `plugins\x64` as usual.
- Resolves #298
Screenshot of `aiff` added to `Settings - Formats`, taken from [CUETools_2.2.4_2023-10-12_git_955881a_Allow_decoding_aiff_using_ffmpeg.dll.zip](https://github.com/gchudov/cuetools.net/files/12889452/CUETools_2.2.4_2023-10-12_git_955881a_Allow_decoding_aiff_using_ffmpeg.dll.zip):
> Allow decoding aiff using ffmpeg.dll

- CUETools.Processor/CUEConfig.cs
The settings of builtin formats were not disabled anymore
in Settings - Formats since e1f8906 (last working in release: 2.1.7).
They were only disabled at the first start of CUETools. As soon as a
settings.txt file was available, this was not the case anymore. 
- Furthermore, this fixes availability of newly added formats like
aiff, if a `settings.txt` file from a previous version of CUETools is
already present.
> Preserve settings for builtin formats

- CUETools.Codecs.MACLib/MACLibDll.cs
APE files are not encoded correctly using CUETools.Codecs.MACLib,
when CUETools is run under 32-bit. This is a regression since the
update of MAC_SDK to 9.04 (#246). No problem under 64-bit.
Affected CUETools versions under 32-bit: v2.2.4, v2.2.3
- MACLibDll.cs, `c_APECompress_Finish()`:
Use `long`, which corresponds to `APE::int64`
> Fix APE encoding under 32-bit

- CUETools.Codecs.ffmpeg/AudioDecoder.cs
Use `ch_layout` instead of the obsolete `channel_layout` and
`ch_layout.nb_channels` instead of obsolete `channels`, which
fixes the following warnings:
- Warning CS0618 'AVCodecParameters.channel_layout' is obsolete:
'use ch_layout'
- Warning CS0618 'AVCodecParameters.channels' is obsolete:
'use ch_layout.nb_channels'
- Warning CS0618 'AVCodecContext.channels' is obsolete:
'use ch_layout.nb_channels'
> Fix ffmpeg channel_layout obsolete warnings

- CUETools.Codecs.ffmpeg/AudioDecoder.cs
Flac files could not be decoded anymore using ffmpeg.dll since ffmpeg
version 5.0 (4.4 and earlier were OK).
- Using ffmpeg 4.4 or earlier, the following message appeared in the
debug output, when decoding flac files using ffmpeg.dll:
`Invalid return value 0 for stream protocol`
- Newer versions of ffmpeg dlls like 5.0 to 6.1 did not show this
output anymore, whereas CUETools got stuck at:
"Analyzing input file..."
- The problem occurred in `av_read_frame()` and the `readPacketCallback()`,
where a value of `len = 0` was returned at the end of flac files.
- Only decoding of flac files using ffmpeg.dll was affected. Other file
formats like aiff, ape, m4a, tta and wv could be decoded properly.
- Return `AVERROR_EOF` instead of `0` in `readPacketCallback()`
- Resolves #300
> Fix decoding flac using ffmpeg.dll plugin

- CUETools.ALACEnc/CUETools.ALACEnc.csproj
- CUETools.ARCUE/CUETools.ARCUE.csproj
- CUETools.CTDB.Converter/CUETools.CTDB.Converter.csproj
- CUETools.Converter/CUETools.Converter.csproj
- CUETools.Flake/CUETools.Flake.csproj
- CUETools.LossyWAV/CUETools.LossyWAV.csproj
- CUETools.eac3to/CUETools.eac3to.csproj
Microsoft.NETCore.App 2.0.0 contains a vulnerability.
- Switch to version 2.0.9 by specifying `RuntimeFrameworkVersion`.
- Fixes the following warnings:
Warning NU1903 Package 'Microsoft.NETCore.App' 2.0.0 has a known
high severity vulnerability,
https://github.com/advisories/GHSA-7mfr-774f-w5r9
- This only concerns the TargetFramework `netcoreapp2.0` of:
CUETools.ALACEnc/CUETools.ALACEnc.csproj
CUETools.ARCUE/CUETools.ARCUE.csproj
CUETools.CTDB.Converter/CUETools.CTDB.Converter.csproj
CUETools.Converter/CUETools.Converter.csproj
CUETools.Flake/CUETools.Flake.csproj
CUETools.LossyWAV/CUETools.LossyWAV.csproj
CUETools.eac3to/CUETools.eac3to.csproj
> Fix Microsoft.NETCore.App vulnerability warnings

- CUERipper/Properties/Resources.Designer.cs
- CUERipper/Properties/Resources.de-DE.resx
- CUERipper/Properties/Resources.resx
- CUERipper/frmCUERipper.cs
The maximum size of embedded album art is 16 MB each.
So far, in case of too large album art, an exception was shown after
ripping the CD, when tagging the files: "Block size too large."
When using libFLAC, an exception appeared at the beginning of ripping
"Exception: unable to initialize the encoder:"
`FLAC__STREAM_ENCODER_INIT_STATUS_ENCODER_ERROR`
- Show an earlier warning, after downloading too large album art
and before starting to rip the CD.
- Switch to `Album art size` `Small`, if the album art is larger than
16 MB and `Embed album art` is set.
- The following warning is shown:
"Selected album art has a size of x bytes, which is too large for
embedding (max 16 MB). Small album art will be used instead."
- This is a follow-up to commit gchudov/taglib-sharp@8590ad0
Prevent taglib …
> CUERipper: Detect too large album art earlier

- .github/workflows/CI-windows.yml
- .github/workflows/release-windows.yml
- Update actions/checkout [1] from v3 to v4
This fixes the following warning:
`build (windows-2022)`
`Node.js 16 actions are deprecated. Please update the following`
`actions to use Node.js 20: actions/checkout@v3.`
- Update actions/upload-artifact [2] from v3 to v4
The `SHA256` hash of the uploaded zip file is now logged.
[1] https://github.com/actions/checkout
[2] https://github.com/actions/upload-artifact
> Update GitHub actions

- CUETools.Codecs.libwavpack/libwavpack.cs
- ThirdParty/submodule_WavPack_CUETools.patch
- Checkout release 5.7.0 of [dbry/WavPack](https://github.com/dbry/WavPack). The previously used
commit in CUETools was dbry/WavPack@e03e8e2 (tag 5.6.0).
- Use the following commands, to update the WavPack submodule to
commit dbry/WavPack@63dd3fa (tag 5.7.0):
```sh
pushd ThirdParty/WavPack/
git fetch
git checkout 63dd3fa3b69fc236cc17886af6d4bd7dbe856125
popd
```
- Update `submodule_WavPack_CUETools.patch`
- Update `CUETools.Codecs.libwavpack/libwavpack.cs`
according to upstream modifications to `include/wavpack.h`
> Update WavPack from 5.6.0 to 5.7.0

- CUERipper/CUERipperConfig.cs
- CUERipper/frmCUERipper.cs
- CUETools.Ripper/Ripper.cs
The `ReadCDCommand` is not detected correctly in some cases. This has
been reported for Plextor drives PX-5224TA and PX-708A.
- Add CUERipper setting `ReadCDCommands`
The setting can be modified by editing `CUERipper\settings.txt`
Remark: CUERipper needs to be closed while editing the file.
- Values for the drive specific setting `ReadCDCommands` are:
0 (ReadCdBEh), 1 (ReadCdD8h), 2 (Unknown/AutoDetect)
Default: 2
- Resolves:
https://hydrogenaud.io/index.php/topic,125668.0.html
> [CUERipper] Add setting to force ReadCDCommand

- Bwg.Scsi/TocEntry.cs
In rare cases, the first track is reported to start at a frame lower
than 150. This leads to an incorrect TOC entry. In such cases, the
`StartSector` is assigned a wrong value of e.g. 16777141 (16777216 - 75).
- Set `StartSector` to `0` in cases,
where a value larger than (16777216 - 150) is reported.
- Fixes #236
- See also:
https://hydrogenaud.io/index.php/topic,125779.0.html
> CUERipper: Fix incorrect TOC entry of first track

- CUETools.Processor/CUESheet.cs
- CUETools/frmCUETools.cs
So far, the CUETools action "Correct filenames" supports reading of
cuesheets in ANSI or UTF-8-BOM format. In case of UTF-8 files without
BOM, issues with special characters can occur.
- Add support for UTF-8 encoded cuesheets without BOM.
- Use method `CUESheet.StreamReader_UTF_ANSI()`.
Detect, if file is `UTF-8-BOM` or `UTF-8` without BOM. Otherwise
fall back to default encoding, which is typically `ANSI`.
- This is a follow-up to #140 (commit d6470d5)
- Fixes #326
> CUETools, Correct filenames: Support UTF-8

- CUETools.Ripper.SCSI/SCSIDrive.cs
Added "ADH20A4P9P57" to the list of devices to use Mode296 as this device is not compatible with Mode294.
> Update SCSIDrive.cs to add support for LITEON ADH20A4P9P57 devices

- CUETools.Processor/CUEConfig.cs
- CUETools.Processor/CUESheet.cs
- CUETools/frmCUETools.cs
This setting allows to enable/disable writing the byte-order mark (BOM)
in case of UTF-8 encoded CUE sheets.
- Add setting:
`WriteUTF8BOM`
Default:
`WriteUTF8BOM=1`
The setting is enabled by default, to preserve previous behavior.
- For now, the setting can be modified by editing `settings.txt` after
closing CUETools or CUERipper:
Use bool value 0, to disable writing the BOM to UTF-8 encoded CUE
sheets.
- The setting is available in the CUETools as well as the CUERipper
`settings.txt` file.
> Add setting for UTF-8-BOM

- CUETools.Processor/CUESheet.cs
EAC log files are encoded using `UTF-16LE` since version 1.0 beta 1.
Since #51 (commit 9f80400) this encoding is preserved in case of EAC
log files, which contain a log checksum. However, only English log
files have been supported so far.
- Also preserve the encoding of EAC log files in different languages,
if they contain a log checksum.
- Just in case an EAC log file with a checksum has been converted
to EOL `LF`, which is fine for CheckLog.exe, preserve `UTF-16LE` too.
- Resolves #330
> Preserve encoding of localized EAC log files

- CUETools.Ripper.SCSI/SCSIDrive.cs
**`LG GH24NSD5`**. Try `Mode296` first.
- See:
https://hydrogenaud.io/index.php/topic,125779.msg1044857.html
> Fix C2 mode for GH24NSD5

- CUETools.Processor/CUEConfig.cs
- CUETools.Processor/CUESheet.cs
If desired, this setting allows disabling writing of the following
comment in dummy CUE sheets:
`REM COMMENT "CUETools generated dummy CUE sheet"`
- Add setting:
`WriteDummyCUESheetComment`
Default:
`WriteDummyCUESheetComment=1`
The setting is enabled by default, to preserve previous behavior.
- The setting can be modified by editing `settings.txt` after
closing CUETools:
Use bool value 0, to disable writing the dummy CUE sheet comment.
- Resolves: #343
> Add setting for writing dummy CUE sheet comment

- CUETools.Ripper.SCSI/SCSIDrive.cs
**`PIONEER BD-RW BDR-UD04`**. Try `Mode296` first.
- According to http://www.accuraterip.com/driveoffsets.htm there are
also submissions from 'BDR-UD04D' drives, with a 'D' at the end.
Those are included too by this commit.
- Resolves #349
> Fix C2 mode for BDR-UD04

- CUETools.Codecs.ffmpeg/AudioDecoder.cs
So far, seeking to `_sampleOffset` has not been implemented in the
CUETools ffmpeg plugin. Seeking is required in case of positive
offsets. Negative offsets have been working before.
- Resolves #352
> ffmpeg: Support positive Offset

- CUETools.Codecs.ffmpeg/AudioDecoder.cs
Restrict seeking to positive Offset to the AIFF file format, when
using ffmpeg.dll for decoding. Other formats are not supported.
- Check for `AV_CODEC_ID_PCM_S16BE`
Remark: Consider only PCM_S16BE, as PCM_S16LE is not supported
by taglib-sharp (Exception: File form type is not AIFF).
> ffmpeg: Seek to positive Offset only for AIFF

- CUETools.Ripper.SCSI/SCSIDrive.cs
**`PLDS DS-8A9SH`**. Try `Mode296` first.
> Fix C2 error mode for PLDS DS-8A9SH

- CUETools.Ripper.SCSI/SCSIDrive.cs
Hi,
This change fixes the error `Exception: Error reading CD: IoctlFailed` for the following drive:
HP
Model: DH-16ACSH-HT2
F/W: JHD6
H/W: 01.01
Recognized by CueRipper as a "hp       DVD A DH16ACSH JHD6".
Issue similar to #178. `Mode294` does not work with this drive, use `Mode296` first.
> Fix C2 error mode for HP DH16ACSH JHD6
